schema:
  format:
    openapi: "3.0.0"
  service_input_type: "LoadBalancedServiceInput"

  types:
    LoadBalancedServiceInput:
      type: object
      description: "Input properties for a loadbalanced Fargate service"
      properties:
        port:
          title: "Port"
          type: number
          description: "The port to route traffic to"
          default: 80
          minimum: 0
          maximum: 65535
        desired_count:
          title: "Desired count"
          type: number
          description: "The default number of Fargate tasks you want running"
          default: 1
          minimum: 1
        task_size:
          title: "Task size"
          type: string
          description: "The size of the task you want to run"
          enum: ["x-small", "small", "medium", "large", "x-large"]
          default: "x-small"
        image:
          title: "Image"
          type: string
          description: "The name/url of the container image"
          default: "public.ecr.aws/nginx/nginx:1.21"
          minLength: 1
          maxLength: 512
        service_discovery_name:
          title: "Service discovery namespace"
          type: string
          description: "The name of the service to register in service discovery"
          minLength: 3
          maxLength: 24
        api_enable_throttling:
          title: "Enable API throttling"
          type: boolean
          default: false
        api_throttling_rate:
          title: "API throttling rate (req/sec)"
          type: number
          description: "Steady-state rate limit for API Gateway stage throttling"
          default: 100
          minimum: 1
        api_throttling_burst:
          title: "API throttling burst"
          type: number
          description: "Burst limit for API Gateway stage throttling"
          default: 200
          minimum: 1
        region:
          title: "AWS Region"
          type: string
          default: "{{ environment.region }}"
      required:
        - service_discovery_name
